#!/usr/bin/env python3
"""PreToolUse gate: scrub Claude.ai session-identifying strings from tool
inputs. Policy: CLAUDE.md 'Commit / PR hygiene'. Wired up in
.claude/settings.json.

For GitHub MCP write tools, the hook rewrites offending string fields in
tool_input and emits `updatedInput` so the tool call proceeds cleanly.
For Bash `git commit` / `gh …` the hook exits 2 with guidance: rewriting
arbitrary shell strings (heredocs, nested quoting) is fragile, so the
model is asked to retry with a cleaned message instead."""
from __future__ import annotations

import json
import re
import shlex
import sys

# Replacements run top-down. The full markdown "_Generated by [Claude Code](…)_"
# form is stripped wholesale before the bare URL pattern would fire, so we
# don't leave dangling markdown fragments behind.
REPLACEMENTS: list[tuple[re.Pattern[str], str]] = [
    (
        re.compile(
            r"_Generated by \[Claude Code\]\((?:https?://)?claude\.ai/code/session_[A-Za-z0-9_-]+\)_"
        ),
        "_Co-Authored by Claude Code_",
    ),
    (
        re.compile(r"(?:https?://)?claude\.ai/(chat|share|code)/[^\s)]*"),
        "Co-Authored by Claude Code",
    ),
    (
        re.compile(r"(?<![A-Za-z0-9_])session_[A-Za-z0-9_-]{8,}"),
        "Co-Authored by Claude Code",
    ),
    (
        re.compile(r"(?<![A-Za-z0-9_])gsd_[A-Za-z0-9_-]{8,}"),
        "Co-Authored by Claude Code",
    ),
]

DETECT = re.compile(
    r"claude\.ai/(chat|share|code)/"
    r"|(?<![A-Za-z0-9_])session_[A-Za-z0-9_-]{8,}"
    r"|(?<![A-Za-z0-9_])gsd_[A-Za-z0-9_-]{8,}"
)

GH_PUBLISHING_SUBCOMMANDS = frozenset({"pr", "issue", "release"})


def invokes_publishing_command(command: str) -> bool:
    """Does this Bash command actually invoke `git commit` or `gh (pr|issue|release)`?

    Uses shlex so `git commit` buried inside a single-quoted payload (e.g. a
    test fixture fed to another program) doesn't trip the gate."""
    try:
        tokens = shlex.split(command, posix=True)
    except ValueError:
        return False
    for i, tok in enumerate(tokens):
        if i + 1 >= len(tokens):
            break
        nxt = tokens[i + 1]
        if tok == "git" and nxt == "commit":
            return True
        if tok == "gh" and nxt in GH_PUBLISHING_SUBCOMMANDS:
            return True
    return False

BASH_REASON = (
    "CLAUDE.md 'Commit / PR hygiene' forbids claude.ai/chat, claude.ai/share, "
    "claude.ai/code, session_*, and gsd_* in commits, PRs, issue comments, "
    "or review replies. Remove the trailer from the command, or replace it "
    "with 'Co-authored-by: Claude <noreply@anthropic.com>' on its own line, "
    "then retry."
)


def clean_string(s: str) -> str:
    out = s
    for pat, repl in REPLACEMENTS:
        out = pat.sub(repl, out)
    # Collapse blank-line runs left by stripped trailers.
    out = re.sub(r"\n{3,}", "\n\n", out)
    return out


def transform(value):
    """Recursively scrub strings in a JSON-ish value. Returns (new, changed)."""
    if isinstance(value, str):
        if not DETECT.search(value):
            return value, False
        return clean_string(value), True
    if isinstance(value, dict):
        changed = False
        new: dict = {}
        for k, v in value.items():
            nv, c = transform(v)
            new[k] = nv
            changed = changed or c
        return new, changed
    if isinstance(value, list):
        changed = False
        new_list: list = []
        for v in value:
            nv, c = transform(v)
            new_list.append(nv)
            changed = changed or c
        return new_list, changed
    return value, False


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except json.JSONDecodeError:
        return 0

    tool_name = data.get("tool_name", "")
    tool_input = data.get("tool_input") or {}

    if tool_name == "Bash":
        command = tool_input.get("command", "") if isinstance(tool_input, dict) else ""
        if not DETECT.search(command) or not invokes_publishing_command(command):
            return 0
        print(f"Blocked: Bash command contains a forbidden session-link. {BASH_REASON}", file=sys.stderr)
        return 2

    cleaned, changed = transform(tool_input)
    if not changed:
        return 0

    json.dump(
        {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "allow",
                "permissionDecisionReason": "Stripped session-identifying link per CLAUDE.md policy.",
                "updatedInput": cleaned,
            }
        },
        sys.stdout,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
